import { type NextPage } from "next";
import Head from "next/head";
import { HelpWidget } from "../components/HelpWidget";
import Box from "../components/Box";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen ">
        <h1 className=" mt-5 text-center text-4xl font-bold text-gray-700">
          Live Chat Application
        </h1>
        <Box />
        <HelpWidget />
      </main>
    </>
  );
};

export default Home;
